name: Generate a build and push to another branch

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
        
      - name: Install all dependencies
        run: npm install
        
      - name: Build
        run: |
          echo "Building project"
          npm run build # The Build command of your project
          # echo "Copying Index files"
          # npm run copy-index  # the copy index.html script
        
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: dist # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Github will automatically add this
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
