name: Generate a build and push to another branch

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
        
      - name: Connect with VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          mkdir -p apps/portfolio && cd apps/portfolio
          
          if [ -d ".git" ]; then
            git stash
            git pull origin master
          else
            git clone -b master {https://github.com/John-Boyes/portfolio} .
          fi
          
          npm install --force
          echo "Building project"
          npm run build # The Build command of your project
          # echo "Copying Index files"
          # npm run copy-index  # the copy index.html script

          pid=$(pm2 pid "portfolio" 2>/dev/null)
          if [ -n "$pid" ]; then
            echo "Reloading application"
            pm2 reload "portfolio"
            pm2 save
          else
            echo "New application"
            pm2 start npm --name "portfolio" -- start
            pm2 startup
            pm2 save
          fi